8338344: Test TestPrivilegedMode.java intermittent fails java.lang.NoClassDefFoundError: jdk/test/lib/Platform
Backport-of: e3a5e265a7747b02b8f828fbedea0dda7246fc51
(cherry picked from commit b1e7e0c507fbb00bba794f5ea3d68cbec8b9a42a)