JBR-1668: minor fixes - temporary fix for compilation issue SystemHotkey.m:74:29: error: format string is not a string literal
(cherry picked from commit b6234f5aa7d46883e4f1bcc9a115fd9546613f53)