8338748: [17u,21u] Test Disconnect.java compile error: cannot find symbol after JDK-8299813
Reviewed-by: sgehwolf
(cherry picked from commit 0f1effe4d216c34705058f55d53f3ad8daa58f3b)