fixup! JBR-6456 Sudden keyboard death on Linux using iBus.
The patch fixes "JBR-7875 src/java.desktop/unix/native/libawt_xawt/awt/awt_InputMethod.c:2605:1: error: label ‘finally’ defined but not used [-Werror=unused-label]".

(cherry picked from commit 17b20784fc6a0d3a7ac7450ed969f339ad486626)