8257798: [PPC64] undefined reference to Klass::vtable_start_offset() Reviewed-by: goetz
(cherry picked from commit 6671330e27d4218cd19b788f83bfd930f31df4a0)