8302491: NoClassDefFoundError omits the original cause of an error
Reviewed-by: coleenp, dholmes
(cherry picked from commit 5685107579f0f00b5eae881311315cec34c1ddcb)