fixup! JBR-2460: Wrong position of input window and no input preview with fcitx and ubuntu 13.04.
The patch fixes "JBR-7875 src/java.desktop/unix/native/libawt_xawt/awt/awt_InputMethod.c:2605:1: error: label ‘finally’ defined but not used [-Werror=unused-label]".

(cherry picked from commit b9e3d11c045b66bce9e11cc58952722f35dcf0e1)