8308429: jvmti/StopThread/stopthrd007 failed with "NoClassDefFoundError: Could not initialize class jdk.internal.misc.VirtualThreads"
Backport-of: 0e501f66dfc52a0e049d4fa39c1fcd24f1f2ee4b
(cherry picked from commit 5520337c11336945fae3065bb7b2bcdd72d680f8)