Revert "fixup! JBR-6456 Sudden keyboard death on Linux using iBus."
This reverts commit 7932169e2559b3efc35c66b7696d2c43ec0457fa.
The issue the reverted fix was for: "JBR-7875 src/java.desktop/unix/native/libawt_xawt/awt/awt_InputMethod.c:2605:1: error: label ‘finally’ defined but not used [-Werror=unused-label]".
The reason: the wrong commit was fixed up.