Revert "fixup! JBR-6456 Sudden keyboard death on Linux using iBus."
This reverts commit 17b20784fc6a0d3a7ac7450ed969f339ad486626.
The issue the reverted fix was for: "JBR-7875 src/java.desktop/unix/native/libawt_xawt/awt/awt_InputMethod.c:2605:1: error: label ‘finally’ defined but not used [-Werror=unused-label]".
The reason: the wrong commit was fixed up.