Revert "8358158: test/jdk/java/io/Console/CharsetTest.java failing with NoClassDefFoundError: jtreg/SkippedException"
This reverts commit 9c74d545147c2eeec187df552037a12b6b476a61.